---
version: 2

references:
  bundle_install: &bundle_install
    run:
      name: Bundle
      command: gem install bundler && bundle install --path vendor/bundle --jobs=4 --retry=3

  cache_bundle_for_lockfile: &cache_bundle_for_lockfile
    save_cache:
      key: ruby3.0.2-Gemfile-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

  cache_bundle: &cache_bundle
    save_cache:
      key: ruby3.0.2-Gemfile
      paths:
        - vendor/bundle

  restore_bundle: &restore_bundle
    restore_cache:
      keys:
        - ruby3.0.2-Gemfile-{{ checksum "Gemfile.lock" }}
        - ruby3.0.2-Gemfile

jobs:
  build:
    docker:
      - image: "ruby:3.0.2"
    working_directory: ~/blog
    steps:
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle_for_lockfile
      - *cache_bundle
      - run: |
          export JEKYLL_ENV=production
          if [[ $CIRCLE_BRANCH == "master" ]]; then
            bundle exec jekyll build
          else
            bundle exec jekyll build --baseurl "/branch/${CIRCLE_BRANCH}"
          fi
      - store_artifacts:
          path: _site
      - persist_to_workspace:
          root: ~/blog
          paths:
            - _site

  deploy:
    docker:
      - image: "google/cloud-sdk"
    working_directory: ~/blog
    steps:
      - run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - attach_workspace: {at: ~/blog}
      - run: |
          if [[ $CIRCLE_BRANCH == "master" ]]; then
            gsutil -m -h "Cache-Control: no-store" rsync -R _site "gs://blog.lawrencejones.dev"
          else
            gsutil -m -h "Cache-Control: no-store" rsync -R _site "gs://blog.lawrencejones.dev/branch/${CIRCLE_BRANCH}"
          fi


workflows:
  version: 2
  test:
    jobs:
      - build
      - deploy:
          filters:
            # I suspect that deploying branch builds is hurting SEO, as Google
            # manages to crawl these pages too. Better to preview locally
            # anyway.
            branches:
              only:
                - master
          requires:
            - build
